language: julia
os:
  - linux
  - osx
julia:
  - 0.3
  - release
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("IntervalTrees")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("IntervalTrees")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

